### ISSUE TITLE
[Request] Sample Apache Configuration

### ISSUE THREAD

**Issue by MiscDev** [gpodder/mygpo#139]
Hi,

Could someone please provide a sample Apache + mod_wsgi configuration file for deploying mygpo?

I'm not familiar with Django and I'm really struggling to get it running correctly. I was able to get the web interface working but I can't get the Basic Auth required for the API working.

Any help would be greatly appreciated.

**Comment by stefankoegl** [comment]
I don't have an Apache configuration because on production gpodder.net runs behind a nginx. I could provide that if its useful for you.

If you want to run mygpo for development purposes, you should be fine with just running the Django development server. You can find some information on that here: https://docs.djangoproject.com/en/2.1/intro/tutorial01/#the-development-server
