### ISSUE TITLE
Unknown Podcast from XXXX

### ISSUE THREAD

**Issue by adamvoss** [gpodder/mygpo#49]
_From @shooftie on July 22, 2017 9:40_

I was having big problems when using GPodder alongside AntennaPod where [feeds were becoming duplicated]((https://github.com/AntennaPod/AntennaPod/issues/2267) ). I tracked this down to the BBC changing their URLs and thus GPodder assuming that these were new podcasts:

`http://www.bbc.co.uk/programmes/p002vsnk/episodes/downloads.rss`

became

`http://podcasts.files.bbci.co.uk/p002vsnk.rss`

The former simply redirects to the latter now.

I have been through most of my podcasts which used the old format and resubscribed using the new URL. However, all of the new URLs result in an 'Unknown Podcast from XXXX' on GPodder.net whilst AntennaPod can interpret the feeds perfectly, titles and images etc.

![image](https://user-images.githubusercontent.com/2161844/28489990-78562408-6f02-11e7-941b-44e238e23438.png)

I've seen this bug mentioned in AntennaPod [here](https://github.com/AntennaPod/AntennaPod/issues/771) and it was stated that:

> We take the title from the (RSS/Atom) feed, not from Gpodder.net itself. We do not sync any feed information apart from the feed's/episode's URL which are used as identifiers

With this being the case, what is AntennaPod doing that GPodder.net is not which enables it to recognise the title and image? I'm happy to send you anything that might help identify the issue, as a donator I am just keen to see this awesome project succeed.

_Copied from original issue: gpodder/gpodder#331_

**Comment by adamvoss** [comment]
_From @elelay on July 22, 2017 14:11_

I think it's because gpodder.net has not parsed the feed.
gpodder.net is composed of different components: one of them is handling episode status sync, another parsing title, description, etc. The latter is not run anymore or not on all feeds. @stefankoegl could explain it better.

**Comment by adamvoss** [comment]
_From @shooftie on July 22, 2017 14:19_

Thanks for responding positively.

Two more questions:

* Will the component responsible for parsing the title, description etc be rekindled or is it dead to the world?
* Would it be tricky to display tags as a comma separated list in the main 'subscriptions' list? I have somewhat mitigated the issue by tagging the feeds with their actual names and having them displayed would be a simple work around.

![image](https://user-images.githubusercontent.com/2161844/28491918-c59aa15c-6f2b-11e7-9a96-a790177a16be.png)

**Comment by adamvoss** [comment]
_From @shooftie on July 22, 2017 15:1_

![image](https://user-images.githubusercontent.com/2161844/28492213-a507dd1e-6f31-11e7-873d-7892476b4a43.png)

**Comment by adamvoss** [comment]
_From @elelay on July 22, 2017 19:47_

I have no idea if it would be possible.
You could also use the gPodder application on desktop.

**Comment by shooftie** [comment]
Yeah, I do but I have different podcasts for different devices... No use listening to the news at the gym! Thanks anyway matey.

**Comment by hovancik** [comment]
I'm also getting some podcasts duplicated (or 3x) with AntennaPod. Also the podcasts that I have unsubscribed long time ago had appeared.

**Comment by shooftie** [comment]
@hovancik Did you use the 'Sync changes now' or 'Full sync now' options in AntennaPod? I found that the issue only happened after doing this. I managed to track down a lot of the duplicates to changes in the feed URL. As for reappearing feeds, that IS strange.

**Comment by hovancik** [comment]
I might. I also tried login to web app but it's also acting weird. On firefox it wont login saying: 

`It seems that another site has linked to gpodder.net to get you to change some data. This will possibly change some of your data / settings!. Do you really want to continue? If in doubt, chose No.`

I can login with chrome, thought.

**Comment by shooftie** [comment]
@hovancik Have tried on Firefox. Works for me. Sorry I can't help mate.

**Comment by adamvoss** [comment]
@shooftie Thank you for testing this out and providing advice!

@hovancik If you could provide more specific details, that could help others in trying to reproduce your issue.  What Firefox are you using (version, platform, etc.)?  What url are you trying to log into?

**Comment by hovancik** [comment]
@adamvoss 
[login](https://gpodder.net/login/)
macOS 10.12.6
Firefox 54.0.1 (64-bit)

**Comment by adamvoss** [comment]
@hovancik Hmm... not a platform I have access to.  Works for me on Linux Mint with FF 54.0 (64-bit), so may be a change in 54.0.1, could be macOS, possibly an extension you have installed, or something else specific to your setup.

I have never seen that message you quoted so don't know where it comes from.  While I'd advise you not to until you know why you are getting the message (there could be a legitimate attack on your system), did you try clicking yes on its prompt?

Running Firefox in  [safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode?redirectlocale=en-US&redirectslug=Safe+Mode) may help in the event it is an extension or plugin causing the problem.

**Comment by hovancik** [comment]
I guess it's some extension or so then. I've tried on Firefox Dev Edition and I could login just fine.

**Comment by shooftie** [comment]
_@elelay from [here](https://github.com/gpodder/mygpo/issues/49#issuecomment-317255329)_
> I think it's because gpodder.net has not parsed the feed.
gpodder.net is composed of different components: one of them is handling episode status sync, another parsing title, description, etc. The latter is not run anymore or not on all feeds. 

It's been 2 months now, am I to assume that these feeds will never be parsed condemning me to the eternal darkness of "Unknown Podcast..."? This is making management of my podcasts trixy at best.

**Comment by FatStephen** [comment]
Anyone gotten answers on this yet in some back room meeting I wasn't aware of?

**Comment by shooftie** [comment]
@FatStephen not here, no.

It's causing me a few problems because it seems that the BBC have redone all of their feeds such that now I am facing more 'Unknown' podcasts than 'Known'.

This is strange because:

Spotlight Tonight: `http://podcasts.files.bbci.co.uk/b08jg5wc.rss` is 'Unknown'

whereas:

Global News: `http://podcasts.files.bbci.co.uk/p02nq0gn.rss` is 'Known'

Both of these have the same updated feed URL but they differ in whether they have been parsed correctly or not.

I have found that by adding the name of the podcast as a tag it at least gives you a pretty shabby workaround.

I stay subscribed to this issue in the hope that if, one day, they are all fixed, we can all have a beer to celebrate.

**Comment by FatStephen** [comment]
A giant part of me wonders whether gPodder has a difficult time as the ones I've noticed aren't recognized don't have metadata on the mp3 files themselves, or at least the ones I've noticed. I've deduced it has nothing to do w/ the age of the podcast, as there are some EDM casts that haven't updated in months that are completely fine, but others like Game Club which updated 10days ago are still "Unknown Podcast from feeds.soundcloud.com" All the ones listed on gPodder's website, the metadata comes up fine from the file the gPodder python desktop tool downloads, but the unknown ones typically don't have any metadata attached at all. Likewise, I've noticed some casts, such as "The WAN Show" stopped tagging their files and have not had their episode list updated since on gPodder (gPodder has the last episode listed as May 1st this year, despite the show being a weekly cast that hasn't taken a known hiatus)

I would just like to know the common thread at this point.

**Comment by shooftie** [comment]
(This)[https://github.com/gpodder/mygpo/issues/49#issuecomment-331786572] was the last I heard of it which seemed to be the final word on the subject, however, the issue remains open and so I live in hope.

**Comment by FatStephen** [comment]
When was the last anyone heard any "official" input on gPodder's development?

**Comment by adamvoss** [comment]
Small point of order: please try to differentiate between gPodder.net and gPodder the desktop application.  They are different code bases and are worked on by largely different people.

**Comment by whiskydotjar** [comment]
The issue is still opened... It's been a couple years...

**Comment by shooftie** [comment]
I found that if I re-searched for the podcast via the discovery tab in the web UI I could find a few that seemed to have the necessary meta. This is rather than using the link provided by the podcaster themselves.

Other than that, I just tag the unknown podcasts so that I at least know their name.

**Comment by gpion** [comment]
Same issue with the following podcast feed:
https://www.rts.ch/emissions/geopolitis/podcasts/?flux=rss/podcast
It create thenths of those "ghost" entries in my subscription list:
![](https://i.imgur.com/wxtSVv9.jpg)

**Comment by stefankoegl** [comment]
Podcast updates have been running more frequently. Please let me know if the problem persists.

**Comment by gpion** [comment]
> Please let me know if the problem persists.

Yes it does, it started with another's feed :

**Comment by gpion** [comment]
Ok, starting at https://gpodder.net/subscriptions/ I've cleared all items list excerpt one 
Triggered a refresh 
and duplicates started to show up few moments later:
![image](https://user-images.githubusercontent.com/2971216/67311564-1e612980-f500-11e9-8944-8739949437b2.png)
I see you closed the issue. So I think I'm going to give up
Sorry.

**Comment by nigelvdv** [comment]
Still a big issue after all these years. Tired of having to clean up all my podcasts every time I install a new ROM and start using gpodder/antennapod combination on my phone.

**Comment by shooftie** [comment]
I gave up with gPodder. It is such a shame because I loved the concept and there is just nothing out there like it. The final straw for me was the non-stop barrage of "Request timed out" or "Server errors" that I was receiving from my client. Even trying to use the gPodder website became a nightmare due to 500s and waiting waiting wating. I've donated but alas there is little else that I can do.

Perhaps the developers could put out a statement indicating how much funding they would need to download a little more RAM on the servers then I could do a charity cake-sale to get them through a few months.

If someone out there has successfully managed self-hosting mygpo then I would really welcome a walk-through. Otherwise, ~~when~~ if I get some free time I will try to do one. Until then I am shuffling OPML files around like a peasant!

**Comment by david-in-perth** [comment]
#49, #89, #109, #330, #439 and #485 all seem to be duplicates (or at least closely related).

**Comment by Ryochan7** [comment]
And none of the above will likely ever get fixed. 4 year old issue

**Comment by shooftie** [comment]
I tried with gPodder but the pain became too much. I donated, I offered, I asked, I pleaded. Eventually I went self hosted.

There is a [great little project] on the go by @akhilrex which solves the problem that I hoped gPodder might have done for me. The developer is on the ball and relatively responsive.

*NB* There are some caveats to the approach of this new project. It is not a drop-in replacement for gPodder but it is a damn sight simpler, less cumbersome and better supported.

**Comment by Ryochan7** [comment]
I have pull requests up and I have put a request in to be added as a project maintainer since some of the older project leads were asking for help. I am fairly proficient with Django and I have played around with the mygpo code on my end some. There are some changes that could be made to improve things. As it is, gpodder.net does not even function as a general podcast directory since most of the views are broken and return 404 errors; an example would be trying to pull up almost any category directory from the main directory list.

That podgrab project seems pretty neat. Never played around with Go.

**Comment by mtedaldi** [comment]
The user @joshproehl posted a workaround, that still seems to work (it did for me today, but generated a 500 about 20% of the time which went away by just refreshing).
https://github.com/gpodder/mygpo/issues/89#issuecomment-413653311

**Comment by Ryochan7** [comment]
That seems to work on my local dev instance if a feed url has not been parsed before. It looks like mygpo will just use the existing data otherwise.
