### ISSUE TITLE
Insanely slow

### ISSUE THREAD

**Issue by mattfj10** [gpodder/mygpo#565]
I'm not sure if this is the right place to put this, but signing up for Gpodder is near impossible. The website is insanely slow and the registration option doesn't seem to work or actually create an account. It takes me 30 seconds to navigate to any page on the website, yet loading any other website is lightning fast for me, and speedtests show my internet speed is normal. Even on my mobile device on using my 4g data it's insanely slow.

Even within an app like antennapod the java socket experiences a timeout exception because it takes so insanely long to get a response from gpodder.

**Comment by debuglevel** [comment]
I experience the same; and AntennaPod often throws exceptions about that synchronisation with mygpo did not work. I wonder what the issue is. Would mygpo need a server sponsor or some crowdfounding? Or can the software/architecture just not handle the increased, probably exponentional grown, load over the last years?

**Comment by cptpcrd** [comment]
> I experience the same; and AntennaPod often throws exceptions about that synchronisation with mygpo did not work. I wonder what the issue is. Would mygpo need a server sponsor or some crowdfounding? Or can the software/architecture just not handle the increased, probably exponentional grown, load over the last years?

I'm also an outside observer, but I've been able to figure a few things out.

Comparing the time to retrieve the main page (served by the Django application in this repository) vs. a static file (served by Nginx, which is probably being used as a reverse proxy) yields some interesting results:

```
# time -p curl -sS https://gpodder.net/ -o /dev/null
real 6.81
user 0.02
sys 0.01
# time -p curl -sS https://gpodder.net/static/reset.css -o /dev/null
real 0.43
user 0.03
sys 0.01
```

The static file loaded much more quickly than the main page. This suggests that the Django application is the bottleneck, and the focus should be on improving performance there, rather than just throwing more resources at the problem (though that may be necessary as part of it).

Now, there's definitely a lot of room for improvement in the code. For example, `mygpo`'s database queries are definitely suboptimal, and during testing, my PR #564 (which deals mainly with database queries) significantly reduced the number of queries. But that may not be the major factor.

`mygpo` only creates as many workers as there are [CPU cores on the current system](https://github.com/gpodder/mygpo/blob/master/conf/gunicorn.conf.py#L5). I'm guessing gpodder.net is probably running on inexpensive cloud hosting, so there are probably 2-4 cores. That would mean 2-4 worker processes running, which may not be sufficient. Increasing the limit to `workers = multiprocessing.cpu_count() * 2` or so *could* yield significant performance improvements.

Then again, I'm guessing based on limited information, and I could be completely wrong about this.

**Comment by ryoung29** [comment]
Updates to the server have been made, and this should be resolved

**Comment by Ryochan7** [comment]
Definitely a lot of work that could be done with the queries. Many large non-indexed searches and duplicate queries being executed per view.
