### ISSUE TITLE
Unable to create new account due to '500 - Internal server error'

### ISSUE THREAD

**Issue by hubertbanas** [gpodder/mygpo#647]
Getting the following when attempting to create new account at https://gpodder.net/register/

![500](https://user-images.githubusercontent.com/2602582/137128366-c965f10e-30f2-48e3-8752-6d2a76f4b28d.png)

**Comment by TBDwarf** [comment]
Same problem to register, error 500...

**Comment by fundatillus** [comment]
No need for further "same issue/problem" comments. 

This issue is confirmed and we'll work on it.

**Comment by Phoenix2683** [comment]
Any update? 24 days at least of not being able to make register new accounts. could we get an update? Thank you for your work!

**Comment by Kofl** [comment]
Push, please fix

**Comment by TBDwarf** [comment]
Hello, I see that the problem seems insoluble, the project is abandoned or it comes from the problem that is very complex to solve?

**Comment by slartibartfass** [comment]
Please fix

**Comment by felixdv** [comment]
Running into the same issue here.

**Comment by dcullifd** [comment]
does anyone know of an alternative way to register?

**Comment by Ryochan7** [comment]
Supposedly the root cause has been found. Who knows when any fix will be implemented

**Comment by alephalpha0** [comment]
Almost three months since last update on this issue... what's going on?

**Comment by Ryochan7** [comment]
Looks like fundatillus has been MIA since November 27. I ended up making my own instance of mygpo in the mean time. Been making changes to the software for the past few weeks. Management of the project has gotten easier with some of the edits.

Custom mygpo:
https://alphagpo.ryochan7.org/

Forked repo:
https://github.com/Ryochan7/alphagpo/

**Comment by xmha97** [comment]
We can't register on [gpodder.net](https://gpodder.net/):
https://twitter.com/CrisFerreiraBR/status/1455888838576967680?s=20&t=ObuGPpuaiZ6SH0I9KTU1Nw
https://twitter.com/xmha97/status/1496071103067959296?s=20&t=ObuGPpuaiZ6SH0I9KTU1Nw
https://twitter.com/jackbteaching/status/1492541016242638851?s=20&t=ObuGPpuaiZ6SH0I9KTU1Nw
https://twitter.com/3duardova/status/1482780554793734146?s=20&t=ObuGPpuaiZ6SH0I9KTU1Nw
https://twitter.com/wy0sa/status/1469694525555810308?s=20&t=ObuGPpuaiZ6SH0I9KTU1Nw
https://twitter.com/Harrisbenedit/status/1396369703128416259?s=20&t=ObuGPpuaiZ6SH0I9KTU1Nw
https://twitter.com/amazingyatt/status/1355427541331243011?s=20&t=ObuGPpuaiZ6SH0I9KTU1Nw
Please fix it.

**Comment by bouktin** [comment]
@stefankoegl and @fundatillus, I'm not overly familiar with Django, but found references to this error: 

[python - RelatedObjectDoesNotExist: User has no userprofile - Stack Overflow](https://stackoverflow.com/a/36317833/311288)

Does that sound like a potential issue ? Did we update Django recently ?

**Comment by Ryochan7** [comment]
I haven't run into this problem on my instance. Looking to the UserProfile issue, the project is supposed to create a UserProfile for a User object upon firing the post_save signal. Not sure why a profile object would not be created during the `user.save()` call a few line before. The Django admin on my instance shows that saved users have an associated UserProfile object created.

https://github.com/gpodder/mygpo/blob/master/mygpo/users/apps.py#L6

**Comment by Eiion** [comment]
As suggested I'm commenting here as well.
Wanting to sync AntennaPod I was given the option to do so via gpodder. When trying to register for an account though I was getting an error 500 (identical to the one that is shown in the original post).
Reading up nen the problem n another issue from (I think it was two years ago) it was recommended to keep reloading to eventually get the registering process done.
I did that in Chrome via PC and also tried multiple times from my phone - every time getting the same error.
Eventually I gave up and commented over here (https://github.com/gpodder/mygpo/issues/527#issuecomment-1053041544) where boutkin advised to comment here instead.

Is there any way I can help you guys out? I'm not a coder but willing that things out on the website or via the podcast app. Just let me know if I can do anything for you.

**Comment by stonespheres** [comment]
> Looks like fundatillus has been MIA since November 27. I ended up making my own instance of mygpo in the mean time. Been making changes to the software for the past few weeks. Management of the project has gotten easier with some of the edits.
> 
> Custom mygpo: https://alphagpo.ryochan7.org/
> 
> Forked repo: https://github.com/Ryochan7/alphagpo/

Ryo, are you suggesting we use this instance for the time being?

**Comment by Ryochan7** [comment]
It would be better if this type of problem would get fixed on the official mygpo instance. It has been several months since this issue has been known. I tried to help contribute to the project here but that didn't work out. I decided to fork this repo and make some improvements to the code base. Been getting into more podcasts since I started and discovering new podcasts was something I was wanting from mygpo.

Also, since the Django requirement is not a fixed version in the requirements.txt file, I guess I will mention that my dev and production instances are running Django 3.2.11. Don't know if that would matter or how different that is from the Django version running on the mygpo server.

**Comment by Eboreg** [comment]
@Ryochan7 I haven't tried anything out by myself, but I think the Django version is key here, because the way Django loads applications [changed in 3.2](https://docs.djangoproject.com/en/3.2/releases/3.2/#what-s-new-in-django-3-2):

> Most pluggable applications define an `AppConfig` subclass in an `apps.py` submodule. Many define a `default_app_config` variable pointing to this class in their `__init__.py`.

> When the `apps.py` submodule exists and defines a single `AppConfig` subclass, Django now uses that configuration automatically, so you can remove `default_app_config`.

In this project, `settings.INSTALLED_APPS` contains `"mygpo.users"` (i.e. the path of the application), and `mygpo/users/__init__.py` does not define a `default_app_config` variable (in fact, I notice this variable was removed in [this commit](https://github.com/gpodder/mygpo/commit/cb1369600e2b44787b0624b4875f587b890f3689), precisely because it is deprecated). This means that, on Django <3.2, a default AppConfig will be used instead of `mygpo.users.apps.UsersConfig`, which in turn means that the `create_missing_profile` signal handler will never be connected.

An upgrade to Django 3.2 should do the trick. I would also suggest that the requirement be changed to `Django==3.2`, since anything under this version will break stuff.

**Comment by AJCxZ0** [comment]
What can we do to help fix this?
Technical expertise, resources, money, etc. won't magically fix the current problem faster, but may help make this valuable service more robust and reliable.

Periodic alerts for failed cient sync failures are costly and the lack of web interface limits management. Loss of browsing is less consequential, but unfortunate.

**Comment by Ryochan7** [comment]
Pretty much going to have to go full DSP beg mode. I can only guarantee my unofficial instance will be up until the end of July. I am back at the point where $10 per month will break me. I am not allowed to be employed.

**Comment by Eboreg** [comment]
If I am correct, it's just a question of the server admin for gpodder.net doing `pip install -U Django` and perhaps restarting the web server. And, preferably, changing `Django<3.3` in requirements.txt to `Django==3.2`. I don't know who this server admin is though.

**Comment by thawn** [comment]
As a workaround for antennapod users: there is also a [nextcloud gpodder plugin](https://github.com/thrillfall/nextcloud-gpodder) available that let's you sync your podcast between clients.

**Comment by Ryochan7** [comment]
So AntennaPod will no longer support the use of gpodder.net with version 2.7.0. It's a shame but this project is pretty much dead.

**Comment by thawn** [comment]
unfortunately, it looks like you are right. I just hope @fundatillus is o.k.

**Comment by fundatillus** [comment]
Hey @thawn, I'm alright. Thank you for your concern. I had to step away when I took a new job. 

I can poke around and see about reinvigorating things. It seems there are some bigger issues than just this... I'll see about getting things cleaned up over the next few days.

**Comment by thawn** [comment]
@fundatillus glad to hear that you are allright :-). Congratulations on your new job!

**Comment by fundatillus** [comment]
> @Ryochan7 I haven't tried anything out by myself, but I think the Django version is key here, because the way Django loads applications [changed in 3.2](https://docs.djangoproject.com/en/3.2/releases/3.2/#what-s-new-in-django-3-2):
> 
> > Most pluggable applications define an `AppConfig` subclass in an `apps.py` submodule. Many define a `default_app_config` variable pointing to this class in their `__init__.py`.
> 
> > When the `apps.py` submodule exists and defines a single `AppConfig` subclass, Django now uses that configuration automatically, so you can remove `default_app_config`.
> 
> In this project, `settings.INSTALLED_APPS` contains `"mygpo.users"` (i.e. the path of the application), and `mygpo/users/__init__.py` does not define a `default_app_config` variable (in fact, I notice this variable was removed in [this commit](https://github.com/gpodder/mygpo/commit/cb1369600e2b44787b0624b4875f587b890f3689), precisely because it is deprecated). This means that, on Django <3.2, a default AppConfig will be used instead of `mygpo.users.apps.UsersConfig`, which in turn means that the `create_missing_profile` signal handler will never be connected.
> 
> An upgrade to Django 3.2 should do the trick. I would also suggest that the requirement be changed to `Django==3.2`, since anything below this version will break stuff.

This fixed it and now I know why we didn't see it in testing... version 3.1.4 was running which met the requirement of <3.3. 

I've manually set the version of Django to 3.2 on the production server. This is not a long term solution, so I'll get to work on migrating to 4.0. 

Thank you everyone for your unreasonably high amount of patience on this. My apologies for not stepping in sooner.

**Comment by Eboreg** [comment]
> This fixed it and now I know why we didn't see it in testing... version 3.1.4 was running which met the requirement of <3.3, but doing a test on a local machine would usually result in 3.2 being installed.

Yep, that's what I meant with my recommendation to change to `Django==3.2` in `requirements.txt`.

Is it any hurry to upgrade to 4.0 though? 3.2 is an LTS release and will be supported until April 2024: https://www.djangoproject.com/download/#supported-versions

**Comment by Eiion** [comment]
Trying to log in via a Google account still shows

`500 - Internal server error.
The service is currently overloaded. Please try again later or contact us.`

**Comment by fundatillus** [comment]
> > This fixed it and now I know why we didn't see it in testing... version 3.1.4 was running which met the requirement of <3.3, but doing a test on a local machine would usually result in 3.2 being installed.
> 
> Yep, that's what I meant with my recommendation to change to `Django==3.2` in `requirements.txt`.
> 
> Is it any hurry to upgrade to 4.0 though? 3.2 is an LTS release and will be supported until April 2024: https://www.djangoproject.com/download/#supported-versions

Glad you mentioned this. We'll plan on sticking with 3.2 until there's a compelling reason not to. Thanks!

**Comment by edvind** [comment]
Tried to register today, got activation mail and all. When I try to login with the new account i get the same error: "500 - Internal server error. The service is currently overloaded. Please try again later or contact us."

Rest of the site works fine.

**Comment by AJCxZ0** [comment]
> Periodic alerts for failed cient sync failures are costly and the lack of web interface limits management. Loss of browsing is less consequential, but unfortunate.

These continue with many tens over the past week. Device removal on the web site - https://gpodder.net/device/(name)/remove - consistently gives a 500 and all other web pages load painfully slowly.

> Technical expertise, resources, money, etc. won't magically fix the current problem faster, but may help make this valuable service more robust and reliable.

Since [gpodder.net](https://gpodder.net/) is hosted by [Tornado VPS](https://tornadovps.com/) and from the single exposed service name appears to have everything hosted on one host running a general purpose OS, in order of decreasing effort the project could
1. Migrate to native cloud based microservices with global CDN, cacheing, transparent scaling, etc.,
2. Tune and optimise the existing platform, application and code to make optimal use of all available resources [e.g. is all the crypto using CPU acceleration?], or
3. Start a [Pateon](https://www.patreon.com/)/[SubscribeStar](https://www.subscribestar.com/)/... crowd fund to get a bigger VPS. It [appears](https://tornadovps.com/order/main/packages/xen/?group_id=10) that the biggest is "only" $660 / year.

**Comment by Frikster** [comment]
> As a workaround for antennapod users: there is also a [nextcloud gpodder plugin](https://github.com/thrillfall/nextcloud-gpodder) available that let's you sync your podcast between clients.

@thawn this is only an option is you're self-hosting?

**Comment by thawn** [comment]
@Frikster either you self-host, or you convince the admin of the nextcloud instance you are using to install the plugin for you.

**Comment by Satalink** [comment]
Maybe someone can fork something like Readarr into Podarr.  It may take a year or so to get it stable, but it would attract dozens of serious developers and quickly grow. I'm sure of it.

**Comment by Satalink** [comment]
I created a fork of [Readarr](https://github.com/Readarr/Readarr) to begin mustering the troops and get a [Podarr](https://github.com/Satalink/Podarr) base initiated.  The *(arr) self-host audience is slightly different, but I think the code base would fit very well for a self-hosted PodCast service. 

I'm very interested in discussing KT (knowledge transfer) from gpodder dev members.   At a high level, the interworkins of Gpodder would need to be mapped into the Poddar fork.   The finish line for Podarr would allow truely self-hosting of podcasts.

There would be some new functionality that would need to be implemented OR it could link into something like [Calibre](https://github.com/kovidgoyal/calibre) to serve up podcasts to your device (replacing gpodder.net) webhost.
